import { mm } from '../units';
import type { Size } from '../units';
import { EncodingType } from './encoding';

// DOCUMENT STRINGS
export const DOCUMENT_TITLE = 'Protect your crypto-wallet seed backup - HoboHodl.com';
export const DOCUMENT_FOOTER_TEXT = 'generated by HoboHodl.com';
export const DOCUMENT_WRITER_HEADER_TEXT = 'Marking stencil';

// DOCUMENT SIZE (A4)
export const DOCUMENT_SIZE: Size = { width: mm(210), height: mm(297) };
export const DOCUMENT_MARGIN_TOP = mm(20);
export const DOCUMENT_MARGIN_H = mm(15);
export const DOCUMENT_MARGIN_BOTTOM = mm(10);
export const EFFECTIVE_PAGE_SIZE: Size = {
  width: DOCUMENT_SIZE.width - 2 * DOCUMENT_MARGIN_H,
  height: DOCUMENT_SIZE.height - DOCUMENT_MARGIN_TOP - DOCUMENT_MARGIN_BOTTOM,
};

// PENS (line widths, in points)
export const PEN_THIN = 0.1;
export const PEN_NORMAL = 0.3;
export const PEN_THICK = 0.5;

// HEADER / FOOTER
export const HEADER_FONT_SIZE = 20;
export const FOOTER_FONT_SIZE = 9;

// WRITER GENERATOR
export const CARD_MARGIN = mm(4);
export const CELL_FONT_SIZE_RANGE: [number, number] = [2.2, 12];
export const WORD_NR_FONT_SIZE_RANGE: [number, number] = [10, 35];

// INPUT RANGES
export const SEED_LENGTH_RANGE: [number, number] = [10, 39];
export const CARD_COUNT_RANGE: [number, number] = [1, 13];
export const CARD_WIDTH_RANGE: [number, number] = [mm(20), DOCUMENT_SIZE.width - 2 * DOCUMENT_MARGIN_H];
export const CARD_HEIGHT_RANGE: [number, number] = [CARD_WIDTH_RANGE[0], CARD_WIDTH_RANGE[1]];
export const CARD_SPLIT_RANGE: [number, number] = [1, 5];
export const CARDS_RADIUS_RANGE: [number, number] = [0, mm(5)];
export const CARDS_PADDING_RANGE: [number, number] = [mm(1), mm(5)];
export const WRITER_COPIES_RANGE: [number, number] = [1, 10];

// INPUT DEFAULTS
export const SEED_LENGTH_DEFAULT = 24;
export const CARD_COUNT_DEFAULT = 2;
export const CARD_SIZE_DEFAULT: Size = { width: mm(100), height: mm(60) };
export const CARD_SPLIT_DEFAULT = 1;
export const CARDS_ENCODING_DEFAULT: EncodingType = EncodingType.Alphabet;
export const CARDS_RADIUS_DEFAULT = mm(1.5);
export const CARDS_PADDING_DEFAULT = mm(1.5);
export const WRITER_COPIES_DEFAULT = 1;

// PREVIEW WARNINGS
export const MIN_CELL_SIZE_MM = mm(1.5);
export const MAX_CELL_ASPECT_RATIO = 2;

// CORNER MARKS
export const CORNER_MARK_RADIUS = mm(0.35);
export const CORNER_MARK_PITCH = mm(1);
